version: "3.9"

services:
  # =========================
  # WEB APP
  # =========================
  db:
    image: postgis/postgis:15-3.4
    container_name: postgis_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - web
      - batch

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GTFS_DATA_PATH: /app/data/GTFS_20260321_v3
      DATA_BASE_PATH: /app/data
      CENSO_DATA_PATH: /app/data/datos_censo_por_manzana_por_comuna
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    profiles:
      - web

  frontend:
    build: ./frontend
    container_name: streamlit_app
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    profiles:
      - web

  # =========================
  # BATCH JOBS
  # =========================
  drive-sync:
    build:
      context: ./backend/scripts/Cargar_datos
      dockerfile: Dockerfile
    container_name: drive_sync
    env_file:
      - .env
    volumes:
      - ./backend/data:/data
    command: ["python", "descargar_datos.py"]
    profiles:
      - batch

  etl-loader:
    build:
      context: ./backend/scripts/Cargar_datos
      dockerfile: Dockerfile
    container_name: etl_loader
    depends_on:
      - db
      - drive-sync
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend/data:/data
    command: ["python", "auto_import.py"]
    profiles:
      - batch

  procesar-censo:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: procesar_censo
    command: ["python", "-m", "scripts.censo"]
    env_file:
      - .env
    environment:
      CENSO_DATA_PATH: /app/data/datos_censo_por_manzana_por_comuna
      CENSO_FORCE_RELOAD: 0
    volumes:
      - ./backend/data:/app/data
      - ./backend/scripts:/app/scripts:ro
      - ./backend/utils:/app/utils:ro
    profiles:
      - batch

  process-gtfs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: process_gtfs
    command: ["python", "-m", "scripts.gtfs"]
    env_file:
      - .env
    environment:
      GTFS_DATA_PATH: /app/data/GTFS_20260321_v3
    volumes:
      - ./backend/data:/app/data
      - ./backend/scripts:/app/scripts:ro
      - ./backend/utils:/app/utils:ro
    profiles:
      - batch

volumes:
  postgres_data: