use std::fs;
use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Context;
use axum::extract::{Query, State};
use axum::http::StatusCode;
use axum::routing::{get, post};
use axum::{Json, Router};
use clap::Parser;
use georoute_core::Graph;
use georoute_core::index::SpatialIndex;
use georoute_core::multimodal::Multimodal;
use georoute_core::transit::Timetable;
use serde::Deserialize;
use serde_json::{Value, json};
use tower_http::cors::CorsLayer;

#[derive(Parser)]
#[command(
    name = "georoute-transit-server",
    about = "HTTP multimodal isochrones over georoute and GTFS"
)]
struct Args {
    /// Foot-profile graph generated by georoute.
    graph: PathBuf,
    /// Unzipped GTFS directory.
    #[arg(long)]
    gtfs: PathBuf,
    /// GTFS service date in YYYYMMDD format.
    #[arg(long)]
    date: i32,
    /// Address to bind.
    #[arg(long, default_value = "127.0.0.1:8090")]
    bind: String,
}

struct AppState {
    graph: Graph,
    index: SpatialIndex,
    timetable: Timetable,
    service_date: i32,
}

#[derive(Deserialize)]
struct IsochroneQuery {
    from: String,
    minutes: f64,
    #[serde(default = "default_departure_hour")]
    departure_hour: u8,
    #[serde(default = "default_max_transfers")]
    max_transfers: usize,
}

#[derive(Deserialize)]
struct IsochronesRequest {
    origins: Vec<[f64; 2]>,
    minutes: f64,
    #[serde(default = "default_departure_hour")]
    departure_hour: u8,
    #[serde(default = "default_max_transfers")]
    max_transfers: usize,
}

fn default_departure_hour() -> u8 {
    8
}

fn default_max_transfers() -> usize {
    4
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let args = Args::parse();
    eprintln!("Loading foot graph {}...", args.graph.display());
    let graph = Graph::from_bytes(&fs::read(&args.graph)?)?;
    if graph.profile != "foot" {
        anyhow::bail!(
            "transit server requires a foot graph, got '{}'",
            graph.profile
        );
    }

    let index = SpatialIndex::build(&graph);
    eprintln!("Loading GTFS {} for {}...", args.gtfs.display(), args.date);
    let timetable = Timetable::from_gtfs(&args.gtfs, args.date, 300.0)
        .map_err(|error| anyhow::anyhow!("loading GTFS: {error}"))?;
    if timetable.num_trips() == 0 {
        anyhow::bail!("GTFS has no active trips for {}", args.date);
    }

    eprintln!(
        "  {} graph nodes, {} stops, {} active trips",
        graph.num_nodes(),
        timetable.num_stops(),
        timetable.num_trips()
    );

    let state = Arc::new(AppState {
        graph,
        index,
        timetable,
        service_date: args.date,
    });
    let app = Router::new()
        .route("/health", get(health))
        .route("/isochrone", get(isochrone))
        .route("/isochrones", post(isochrones))
        .layer(CorsLayer::permissive())
        .with_state(state);

    let listener = tokio::net::TcpListener::bind(&args.bind)
        .await
        .with_context(|| format!("binding {}", args.bind))?;
    println!("georoute-transit-server listening on http://{}", args.bind);
    axum::serve(listener, app).await?;
    Ok(())
}

async fn health(State(state): State<Arc<AppState>>) -> Json<Value> {
    Json(json!({
        "status": "ok",
        "engine": "georoute",
        "profile": "transit",
        "algorithm": "raptor_multimodal",
        "service_date": state.service_date,
        "stops": state.timetable.num_stops(),
        "trips": state.timetable.num_trips(),
    }))
}

async fn isochrone(
    State(state): State<Arc<AppState>>,
    Query(query): Query<IsochroneQuery>,
) -> Result<Json<Value>, (StatusCode, String)> {
    validate_request(query.minutes, query.departure_hour, query.max_transfers)?;
    let origin = parse_coord(&query.from)?;
    let request = IsochronesRequest {
        origins: vec![origin],
        minutes: query.minutes,
        departure_hour: query.departure_hour,
        max_transfers: query.max_transfers,
    };
    let result = build_isochrones(state, request).await?;
    if result["features"].as_array().is_none_or(Vec::is_empty) {
        return Err((
            StatusCode::UNPROCESSABLE_ENTITY,
            "georoute did not produce a transit isochrone".to_string(),
        ));
    }
    Ok(Json(result))
}

async fn isochrones(
    State(state): State<Arc<AppState>>,
    Json(request): Json<IsochronesRequest>,
) -> Result<Json<Value>, (StatusCode, String)> {
    validate_request(
        request.minutes,
        request.departure_hour,
        request.max_transfers,
    )?;
    if request.origins.is_empty() || request.origins.len() > 500 {
        return Err((
            StatusCode::BAD_REQUEST,
            "origins must contain between 1 and 500 coordinates".to_string(),
        ));
    }
    for origin in &request.origins {
        validate_coord(*origin)?;
    }
    Ok(Json(build_isochrones(state, request).await?))
}

async fn build_isochrones(
    state: Arc<AppState>,
    request: IsochronesRequest,
) -> Result<Value, (StatusCode, String)> {
    tokio::task::spawn_blocking(move || {
        let engine = Multimodal::new(&state.graph, &state.index, &state.timetable);
        let departure_seconds = f64::from(request.departure_hour) * 3600.0;
        let max_seconds = request.minutes * 60.0;
        let mut features = Vec::new();
        let mut failed_origins = Vec::new();

        for (origin_index, origin) in request.origins.iter().enumerate() {
            let mut ring = engine.isochrone_ring(
                *origin,
                departure_seconds,
                max_seconds,
                request.max_transfers,
            );
            if ring.len() < 3 {
                failed_origins.push(origin_index);
                continue;
            }
            if ring.first() != ring.last() {
                ring.push(ring[0]);
            }
            features.push(json!({
                "type": "Feature",
                "properties": {
                    "kind": "isochrone",
                    "mode": "transit",
                    "minutes": request.minutes,
                    "departure_hour": request.departure_hour,
                    "origin_index": origin_index,
                    "engine": "georoute",
                    "profile": "transit",
                    "algorithm": "raptor_multimodal",
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [ring],
                }
            }));
        }

        json!({
            "type": "FeatureCollection",
            "features": features,
            "metadata": {
                "engine": "georoute",
                "profile": "transit",
                "algorithm": "raptor_multimodal",
                "service_date": state.service_date,
                "minutes": request.minutes,
                "departure_hour": request.departure_hour,
                "requested_origins": request.origins.len(),
                "generated_isochrones": features.len(),
                "failed_origins": failed_origins,
            }
        })
    })
    .await
    .map_err(internal_error)
}

fn validate_request(
    minutes: f64,
    departure_hour: u8,
    max_transfers: usize,
) -> Result<(), (StatusCode, String)> {
    if !minutes.is_finite() || !(1.0..=180.0).contains(&minutes) {
        return Err((
            StatusCode::BAD_REQUEST,
            "minutes must be between 1 and 180".to_string(),
        ));
    }
    if departure_hour > 23 {
        return Err((
            StatusCode::BAD_REQUEST,
            "departure_hour must be between 0 and 23".to_string(),
        ));
    }
    if !(1..=8).contains(&max_transfers) {
        return Err((
            StatusCode::BAD_REQUEST,
            "max_transfers must be between 1 and 8".to_string(),
        ));
    }
    Ok(())
}

fn parse_coord(value: &str) -> Result<[f64; 2], (StatusCode, String)> {
    let mut parts = value.split(',');
    let lon = parts
        .next()
        .and_then(|part| part.trim().parse::<f64>().ok());
    let lat = parts
        .next()
        .and_then(|part| part.trim().parse::<f64>().ok());
    if parts.next().is_some() || lon.is_none() || lat.is_none() {
        return Err((
            StatusCode::BAD_REQUEST,
            "from must use lon,lat format".to_string(),
        ));
    }
    let coord = [lon.unwrap(), lat.unwrap()];
    validate_coord(coord)?;
    Ok(coord)
}

fn validate_coord(coord: [f64; 2]) -> Result<(), (StatusCode, String)> {
    if !coord[0].is_finite()
        || !coord[1].is_finite()
        || !(-180.0..=180.0).contains(&coord[0])
        || !(-90.0..=90.0).contains(&coord[1])
    {
        return Err((
            StatusCode::BAD_REQUEST,
            "coordinate is outside WGS84 bounds".to_string(),
        ));
    }
    Ok(())
}

fn internal_error(error: tokio::task::JoinError) -> (StatusCode, String) {
    (StatusCode::INTERNAL_SERVER_ERROR, error.to_string())
}
