[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7MYiq-EANOFyYlkKlEI_-kWcLMqlc1mQOYfg-QOMsbCOBu4x1Ln6N4fC00hO8oU5dxlRnZzbUM3PgABOTaoqrjKlEFvrc5uOFr8Oe2diT9pb0cOkLtoCCyBuQKfftKy5fm53DnKLgvjcZRZEmL68QQ0z7Wr723x4yWLuCPuYWEM4qQk22akIXiUXV7x_MwaibjqdMaCgYKAeYSARcSFQHGX2Mix4u6-Jj5FLbeIGi5tVlA_A0206","token_type":"Bearer","refresh_token":"1//0hPDD3K5SggnWCgYIARAAGBESNwF-L9IrX7gzPu5l4IBihA9FCYMWzXgPrbWlxgG8Vg0qTyYDc-fC3RCRvqrLF1B4Kac3uuTUKyQ","expiry":"2026-04-10T01:14:24.4045584-04:00","expires_in":3599}
team_drive = 

